# Generated by Django 2.0 on 2019-05-17 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_read_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='read_num',
        ),
        migrations.AddField(
            model_name='readnum',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Article'),
        ),
    ]
