# Generated by Django 2.0 on 2019-05-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190517_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='article',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
